services:
  web-study:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GOOGLE_TAG_ID: ${GOOGLE_TAG_ID}
        NEXT_PUBLIC_SITE_URL: ${SITE_URL:-https://webtech.yehia.dev}
    image: web-study:latest
    container_name: web-study
    ports:
      - "7821:3000"
    restart: unless-stopped
